NVE/regObs4

README.md

Har lagt til en del info om oppsett av miljø for å teste på Android-dings.
Mulig dette er for detaljert.

Added detailed debug instructions

---

src/app/core/services/geo-position/geo-position-log.interface.ts
src/app/core/services/geo-position/geo-position.service.ts
src/app/modules/gps-debug/components/gps-debug/gps-debug.component.ts

pga. mulige endringer i siste versjon av ionic eller oppgradering av Node

Fiksa kompileringsfeil knytta til PositionError

---

src/app/modules/shared/components/header/header.component.html
src/app/modules/shared/components/header/header.component.ts
src/app/modules/side-menu/components/side-menu.component.ts
src/app/pages/tabs/tabs.page.scss
src/global.scss

- RO-1142 - knapp for å gjemme split-pane
- RO-1163 - mørkere blå farge på tab selected
- RO-1140 - kontakt oss router til mail og rapporter feil til tilbakemeldingsskjema

fix dead links, close button on side panel, and darker tab color

---

src/app/modules/auth/pages/auth-callback/auth-callback.page.ts
src/app/modules/auth/services/regobs-auth.service.ts

Redirect user to home (map) when logging out. This works on desktop and should also work on app. This needs to be tested when we release a new version.

route logout button to map page

---

src/app/modules/map/components/map/map.component.html
src/app/modules/map/components/map/map.component.scss
src/app/modules/map/components/map/map.component.ts

Adds zoom level info for debugging map styles etc

Add zoom level debug info

---

src/app/modules/map/components/map/map.component.ts

Fikset også en feil. GroupLayer for offline-lag hadde ikke ID, så det ble laget ny GroupLayer hver gang vi oppdaterte offline-kartlag. Kunne bli mange lag oppå hverandre etterhvert...

Nå fjerner vi kartlag når offline-pakke slettes

---

src/app/modules/map/components/map/map.component.ts

Fungerer helt OK uten noe max zoom constraint til testing

Remove max zoom constraint for offline layers

---

src/app/core/services/offline-map/offline-map.service.ts
src/app/modules/map/components/map/map.component.ts

Nå venter vi 5 sek fra en kartpakke er pakket ut før jeg lager nytt kartlag.
Har også gjort om varsling om nye kartpakker og sletting av kartpakker, slik at vi ikke legger til kartlag som allerede er lagt til fra før.

Forsøk på å fikse at nye kartpakker ikke ble lastet

---

package-lock.json
src/app/app.component.ts
src/app/core/services/offline-map/offline-map.service.ts
src/app/modules/map/components/map/map.component.ts
src/app/modules/shared/services/logging/console-logging.service.ts
src/app/modules/shared/services/logging/file-logging.config.ts
src/app/modules/shared/services/logging/file-logging.service.ts
src/app/modules/shared/services/logging/sentry.service.ts
src/app/pages/home/home.page.ts
src/app/pages/user-settings/user-settings.page.html
src/app/pages/user-settings/user-settings.page.ts

Her er første utkast til funksjon for å logge på telefon og funksjon for å sende loggfiler til oss.
Funksjonen for å sende epost ligger under meny / innstillinger / avanserte innstillinger.
Det er i hvert fall to utfordringer jeg ikke har løst:
- noen logge-kall blir ikke logget. Jeg vet ikke hvorfor, men jeg ser at konsollet i nettleser inneholder mer logging enn det som lagres på fil
- native logging til konsollet blir ikke logget. Vet ikke hvordan vi kan løse det, men fant en side hvor det sto om å fange logging til konsoll. (https://www.damirscorner.com/blog/posts/20180119-SharingConsoleLogFromIonicApps.html) Vet ikke om det kan funke, men kanskje verdt en titt?

RO-1311 Logg til fil og send på epost

---

src/app/app.component.ts
src/app/modules/shared/services/logging/console-logging.service.ts
src/app/modules/shared/services/logging/file-logging.config.ts
src/app/modules/shared/services/logging/file-logging.service.ts
src/app/modules/shared/services/logging/sentry.service.ts
src/app/pages/user-settings/user-settings.page.html
src/app/pages/user-settings/user-settings.page.ts

Cherry picked commits from #50

Add file logging

---

src/global.scss

Vise større bilder i modal når man trykker på de i bildekarusell (vise original størrelse).

make images 100% in modal

---

src/app/modules/side-menu/components/filter-menu/filter-menu.component.html
src/app/modules/side-menu/components/filter-menu/filter-menu.component.ts

- Foreløpig Mock data for observasjonstyper fordi hjelpemetode for å hente ut typene ligger i common prosjektet som ikke implementert i app enda.

bytter observasjonstyper basert på naturfare

---

src/app/core/services/offline-map/offline-map.service.ts
src/app/pages/offline-map/offline-package-modal/offline-package-modal.component.html

Save available diskspace in local variable in offline map service.
Trigger update of available diskspace on load and when offline packages changes.

Save available diskspace in local variable in offline map service.

---

package-lock.json
package.json
src/app/modules/edit-picture-info-modal/edit-picture-info-modal.component.ts
src/app/modules/shared/components/geo-name/geo-name.component.spec.ts
src/app/modules/shared/components/geo-name/geo-name.component.ts
src/app/modules/side-menu/components/check-days-or-weeks-back/check-days-or-weeks-back.component.html
src/app/modules/side-menu/components/filter-menu/filter-menu.component.scss
src/app/modules/side-menu/components/show-filter-criteria/show-filter-criteria.component.html
src/app/modules/side-menu/components/show-filter-criteria/show-filter-criteria.component.ts

Add current geoHazard in show-filter-criteria.
Trim out whitespace for edit-picture-info-component

fix show criteria, update translations, css bugfix

---

package-lock.json
package.json
src/app/modules/shared/components/geo-name/geo-name.component.spec.ts
src/app/modules/shared/components/geo-name/geo-name.component.ts
src/app/modules/side-menu/components/check-days-or-weeks-back/check-days-or-weeks-back.component.html
src/app/modules/side-menu/components/show-filter-criteria/show-filter-criteria.component.html

- La til nynorsk oversettelser
- Fikset mellomrom problem på kun dagens observasjoner
- Fikset at geoHazard i show-filter nå endres når man endrer språk

fikse visning av filterkriterier

---

config.xml

Changed SplashScreenDelay and FadeSplashScreenDuration to the same values as Ionic Starter templates

ro-1301 - blank screen

---

package-lock.json
package.json
src/app/modules/auth/services/regobs-auth.service.ts

Innlogging sluttet å funke etter vi oppgraderte pakkene.
Denne fiksen får det til å funke igjen.

Rulla oppgradering av ionic-appauth tilbake til forrige versjon

---

package-lock.json
package.json

RO-1510: Sikkerhetsoppgradering

---

src/app/modules/map/services/map-search/map-search.service.spec.ts
src/app/modules/map/services/map-search/map-search.service.ts
src/app/modules/map/services/map-search/norwegian-search-result.model.ts
src/settings.ts

Tatt i bruk nytt api for å søke etter stedsnavn.
Nå viser vi også stedsnavn-type hvis man har valgt nynorsk. Har også lagt inn litt mer intelligens for å formatere stedsnavnet, slik at kommune ikke blir vist for treff på fylke f.eks.
Mesteparten av koden er kopiert fra web:
http://tfs01.nve.no:8080/tfs/tfs2012_nve/_git/regObs_git/pullrequest/2468

RO 1504: Tatt i bruk nytt api for å søke etter stedsnavn

---

src/app/core/services/offline-map/offline-map.service.ts
src/app/modules/side-menu/components/side-menu.component.html
src/app/pages/offline-map/offline-map.page.html
src/app/pages/offline-map/offline-map.page.ts
src/app/pages/offline-map/offline-package-modal/offline-package-modal.component.html
src/assets/i18n/de.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/assets/i18n/it.json
src/assets/i18n/nb.json
src/assets/i18n/nn.json
src/assets/i18n/sl.json
src/assets/i18n/sv.json

Adds translations for offline map. Only adds norwegian, nynorsk and english. English is fallback, so should be ok.

Add translations for offline map

---

src/settings.ts

Har kommentert ut valget for fransk, slik at man ikke kan velge fransk språk.

RO-1512: Deaktivert fransk

---

ios/App/App.xcodeproj/project.pbxproj
ios/App/App/de.lproj/InfoPlist.strings
ios/App/App/en.lproj/InfoPlist.strings
ios/App/App/fr.lproj/InfoPlist.strings
ios/App/App/nb.lproj/InfoPlist.strings
ios/App/App/nn.lproj/InfoPlist.strings
ios/App/App/sl.lproj/InfoPlist.strings
ios/App/App/sv.lproj/InfoPlist.strings
package-lock.json
package.json

Add translations to ios app

---

src/settings.ts

Reverts NVE/regObs4#118
Nå vil vi aktivere fransk igjen

Revert "RO-1512: Deaktivert fransk"

---

src/app/modules/registration/pages/snow/avalanche-evaluation/avalanche-evaluation.page.html

Show 0 - ikke vurdert

---

src/app/app.component.ts
src/app/core/services/app-version/app-version.service.ts
src/app/core/services/data-marshall/data-marshall.service.ts
src/app/modules/analytics/services/analytic.service.ts
src/app/modules/auth/factories/auth-factory.ts
src/app/modules/auth/services/regobs-auth.service.ts
src/app/modules/shared/services/logging/url-utils.spec.ts
src/app/modules/shared/services/logging/url-utils.ts

Forsøk på å finne ut hvorfor iOS kan kræsje ved oppstart etter innlogging:
Nå logger vi side-navigering og ganske detaljert hva som skjer når vi får får callback fra innlogging.
Side-navigering blir logget hvis du skrur på GA, men vi logger ikke dette ellers. Før nå.

RO-1542: Legge til mer logging under ruting, pålogging, mm

---

src/settings.ts

Revert "Revert "RO-1512: Deaktivert fransk""

---

src/assets/i18n/fr.json
src/assets/i18n/nn.json

Update translations for french and nn

---

src/app/modules/side-menu/components/side-menu.component.html
src/app/modules/side-menu/components/side-menu.component.ts
src/app/pages/user-settings/user-settings.page.html
src/app/pages/user-settings/user-settings.page.ts

Sånn ser det ut nå:
Har brukt samme ledetekst som i start-vegviser.

RO-1508: Flytta språkvalg fra innstillinger til hovedmeny

---

src/assets/i18n/de.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/assets/i18n/nb.json
src/assets/i18n/nn.json
src/assets/i18n/sl.json
src/assets/i18n/sv.json

Update soil translation key

---

src/app/modules/map-image/map-image.component.ts

Fixes a bug where no map layers where shown for observations outside of norway, but inside norway's bounding box

Use a border polygon when choosing map layer

---

src/app/core/http-interceptor/ApiInterceptor.ts
src/app/core/services/observation/observation.service.ts
src/app/pages/my-observations/components/sent-list/sent-list.component.ts

Det er fortsatt et problem med at "Mine observasjoner ikke får med seg de observasjonene du nettopp sendte inn.
Dette løser vi for seg.

RO-1437: Fått "Mine observasjoner" til å virke igjen ved å ta i bruk ny funksjon i API'et

---

src/app/modules/common-registration/services/registration/registration.service.ts
src/app/pages/my-observations/components/sent-list/sent-list.component.ts

RO-1437/RO-1600: Update my observations and map after submission
