- src/app/components/img-swiper/img-swiper.component.scss
- src/app/core/services/breakpoint.service.ts
- src/app/core/services/user-setting/user-settings.default.ts
- src/app/modules/registration/components/failed-registration/failed-registration.component.ts
- src/app/modules/registration/pages/danger-obs/add-or-edit-danger-obs-modal/add-or-edit-danger-obs-modal.page.ts
- src/app/modules/shared/components/add-menu/add-menu.component.html
- src/app/modules/shared/components/add-menu/add-menu.component.ts
- src/app/modules/shared/components/header/header.component.html
- src/app/modules/shared/components/header/header.component.scss
- src/app/modules/shared/components/header/header.component.ts
- src/app/modules/shared/components/input/select/select.component.html
- src/app/modules/shared/components/input/select/select.component.ts
- src/app/modules/side-menu/components/side-menu.component.html
- src/app/modules/side-menu/components/side-menu.component.scss
- src/app/modules/side-menu/components/side-menu.component.ts
- src/app/pages/user-settings/user-settings.page.html
- src/app/pages/user-settings/user-settings.page.ts
- src/assets/icon/menuanimation.svg
- src/assets/icon/menuarrow.svg
- src/global.scss
This change includes several customizations for the desktop version of the app and some updates to the app.
WEB
- RO-1175: Fix dropdown under 'skredproblem'
- RO-1173: Add arrow icon and slide in animation for split pane on side menu
- RO-1166: If observation fails the send email button tries to open the computers mail client and the edit button redirects back to the observation
- RO-1174: Remove start trip option for desktop
- RO-1176: Select component did not display properly due to a missing ngModel binding to the selected value. 
- Change language dropdown to be popover on desktop
APP (Changes that are for both the mobile app and web version)
- RO-1180: Default map is now ESRI World Topo + Kartverket instead of just kartverket
- Change highlighted tab color for more contrast and …
> Fix selects, change default map, remove start trip on desktop

- src/app/pages/offline-map/offline-map.page.html
- src/app/pages/offline-map/offline-map.page.ts
Dette er en liten fiks av tabellen med oversikt over kartpakker på tlf.
Har også lagt inn kolonne for dato/versjon, selv om vi ikke har det ennå
> Fjerner visning av NaN hvis vi ikke har størrelse på pakka

- src/app/core/services/offline-map/offline-map.service.ts
- src/app/modules/map/components/map/map.component.ts
Skrur av webserver ved pause og på igjen når appen er tilbake.
Mulig koden burde ryddes litt i. Dette var bare en kjapp test for å sjekke ut en teori.
Har også fikset feil koordinatsystem i flyTo()-metoden, så vi havner på riktig sted. Dette har ingenting med levering av offline-fliser å gjøre, jeg bare sneik det inn.
Testet på Android og iPhone 8.
> RO-1218: Forsøk på fiks av "Tiles slutter å laste etter en stund (offlinekart)"

- src/app/core/helpers/leaflet/map-item-marker/map-item-marker.ts
- PictureMarkerSymbol now used Pixels for everything on width, height and newly added x-offset
> move to pxs for width, height, add x-offset

- src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.html
- src/app/modules/registration/components/set-location-in-map/set-location-in-map.component.ts
- src/app/modules/registration/pages/dirt/landslide-obs/landslide-obs.page.ts
- src/app/modules/registration/pages/obs-location/obs-location.page.html
- src/app/modules/registration/pages/obs-location/obs-location.page.ts
- src/app/modules/registration/pages/set-avalanche-position/set-avalanche-position.page.html
- src/app/modules/registration/pages/set-avalanche-position/set-avalanche-position.page.ts
- src/app/modules/registration/pages/set-damage-location/set-damage-location.page.html
- src/app/modules/registration/pages/set-damage-location/set-damage-location.page.ts
- src/app/modules/registration/pages/snow/avalanche-obs/avalanche-obs.page.ts
"Første versjon" av stedfesting av observasjon.
Flg. skal virke:
- at du kan plassere en observasjon på et sted og endre plassering
Vi må sjekke at denne fungerer godt sammen med RO-1224, når denne er på plass.
Flg. gjenstår, og vil bli skilt ut i egne oppgaver:
- løse ørten TODO's i koden
- ikonene er uklare
- tegne strek mellom GPS-posisjon og observasjons-markør
- vise tidligere brukte/navngitte lokasjoner
- velge en tidligere brukt/navngitt lokasjon som lokasjon
- stedfesting av start/stopp på skredhendelse
- stedfesting av skader for vann-observasjoner
> RO 1229: Stedfesting av observasjon

- package.json
The artifacts in this repository are governed by the Norwegian Licence
for Open Government Data (NLOD) 2.0 -- declare this in the
`package.json` so that it is known to future users.
Fixes: nve/regObs4#18
Related issue: spdx/license-list-XML#1261
> chore: Explicitly state the license

- src/app/modules/map/components/map/map.component.ts
Se logge-utskrift i Jira: https://nveprojects.atlassian.net/browse/RO-1310
Å iterere over enums er skummelt. Kom gjerne med tips til hvordan jeg kan gjøre dette bedre, men nå får vi i hvert fall ikke dobbelt opp med "gruppe-lag".
> RO-1310: Fjernet duplikate kartlag

- src/app/modules/map/components/map/map.component.html
- src/app/modules/map/components/map/map.component.ts
- src/app/pages/home/home.page.ts
Solveig oppdaget at klikk på observasjons-ikoner i kartet sluttet å virke etter man hadde byttet bakgrunnskart.
Årsaken var at det ble laget nye click-handlere hver gang man endret bakgrunnskart, fordi mapReady.emit() ble kalt etter bakgrunnskart ble byttet (og alle lag lagt til på nytt).
Klikk-handler ble derfor fyrt av dobbelt så mange ganger, så de nullet ut hverandre (som om man klikker på ikonet på nytt for å skjule visninga av observasjonen nederst).
Det er ikke nødvendig å lage nye klikk-handlere når kartene byttes ut, fordi klikk-handlere og datakilder matcher mot ID på lagene, og de er de samme, selv om det er nye lag.
> RO-1228-Duplicate click handlers

- package-lock.json
- src/app/core/models/support-tile.model.ts
- src/app/core/models/user-settings.model.ts
- src/app/core/services/popup-info/popup-info.service.ts
- src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.html
- src/app/modules/side-menu/components/support-tiles-menu/support-tiles-menu.component.ts
- src/settings.ts
This change throws up a popup every time the user activates
an online-only support map. It also rebases some of the
popup code, since it started to have quite a bit of copied
code.
> Make it blatantly clear what's online-only

- src/app/modules/registration/pages/ice/ice-thickness/ice-thickness.page.ts
Hvordan teste:
1. Registrer istykkelse
2. Velg ja på overvann og sett f.eks 2 cm på overvannets tykkelse (feltet som dukker opp når man skriver Ja), 
3. Velg nei på overvann
4. Gå tilbake til min observasjon
5. Velg istykkelse
6. Det skal nå ikke være noe felt for overvannets tykkelse. Feilen var at dette feltet ble hengende igjen med verdien du satte.
> RO-1532: Nå fjerner vi overvannshøyde hvis overvann før boring ikke er valgt

- src/app/core/services/offline-map/offline-map.service.ts
- src/assets/i18n/en.json
- src/assets/i18n/nb.json
- src/assets/i18n/sv.json
Hvis det feiler når vi prøver å skrive fila til disk, vil vi nå prøve fire ganger til før vi gir opp.
Om vi har mindre enn 300MB på telefonen, viser vi den gamle feilmeldinga om at du bør sjekke om du har nok plass.
Hvis vi har mer plass enn dette, viser vi en mer generell feilmelding.
Har også forsøkt å forenkle koden litt ved å splitte opp noen av de lange funksjonene.
Testet på Android (dog ikke med å fylle opp tlf, men med å trikse med 300MB-grensa).
> RO-1541: Håndere feil under utpakking på en smartere måte

- src/app/core/services/helpers/helper.service.ts
- src/app/pages/offline-map/offline-map.page.html
- src/app/pages/offline-map/offline-map.page.ts
- src/assets/i18n/en.json
- src/assets/i18n/nb.json
- src/assets/i18n/nn.json
Nå viser vi alle kartpakker som er på telefonen, i tillegg til de du laster ned eller har lagt i kø.
Har også jobbet litt med å redusere plass i "liste-overskriften" for å få plass til hele teksten på små skjermer.
Løsningen ble å bruke fire kolonner i stedet for tre, da jeg ikke fikk til å overstyre overflow: hidden. Synes det så greit ut likevel.
Har også fikset teksten i bekreftelses-popupen som kommer opp hvis du prøver å slette en nedlasta kartpakke. Denne var nok ikke helt ferdig.
Det forslaget som dukket opp på fredag om å vise "Trykk på en rute i kartet for å laste ned" i stedet for "0 Pakker 0 MB ### GB ledig" før man har lastet ned noe, forkastet jeg, fordi jeg mener det er viktigere å kunne se om man har plass. Vi har en egen Jira-oppgave på dette og har allerede et forslag på …
> Vise også nedlastede pakker i lista

- src/app/modules/map/components/map/map.component.ts
Tipper årsaken var at options ikke ble sendt med til kartlaget når vi valgte GeodataLandskap-kartet. 
Det funket i hvert fall bra i Android etter det.
> RO-1551: Fiks av at offline-kart vises i stedet for Geodata-kartet selv om man er online

- src/app/pages/offline-map/offline-map.page.ts
Nå husker vi hvilke pakker som har feilet i tidligere nedlastingssesjon, og markerer disse i kartet når vi åpner offlinekart-oversikten.
Det var tidligere forsøk på å løse dette, men rød-markeringa ble forsøkt satt før map'en som holdt på rutene ikke var ferdig oppbygd, derfor ble ikke ruta tegnet med rød bakgrunn.
Synes det er litt vanskelig å blande RXJS med tilstand i klassen slik vi har her; fant ikke noen bedre løsning. Hadde vært stilig å hatt en Observable som sa ifra når alle features var tegnet ferdig, slik at vi kunne vente med å sette stil til denne var klar.
> RO-1529: Fiks av at ruter mistet "rødmarkeringa" hvis man lukket siden og gikk inn igjen

- src/settings.ts
Vi har fått Octopus til å virke igjen og har rullet fransk i API'et ut til demo. Da kan vi gjøre det mulig å teste dette i appen
> Aktiverer fransk språk igjen

- src/app/core/services/offline-map/offline-map.service.ts
- src/assets/i18n/en.json
- src/assets/i18n/nb.json
- src/assets/i18n/nn.json
- src/assets/i18n/sv.json
Det er denne statusen som nå er oversatt:
Dette blir oversatt i servicen idet feilen skjer, så hvis du bytter språk etter at det feilet, får du ikke oversatt det på nytt. Tenkte det var godt nok.
> PR-1528: Har oversatt hardkodet feilstatus som vises i popup'en for en kartpakke

- src/app/app.providers.ts
- src/app/core/services/shortcut/shortcut.service.ts
- src/app/modules/auth/factories/auth-factory.ts
- src/app/modules/common-registration/registration.module.ts
Det feilet etter registreringa var sendt inn i RegobsApiSyncCallbackService.removeAllNewAttachments() fordi man brukte feil versjon av OfflineDbNewAttachmentService, som er for web.
Så det er egentlig bare endringen i RegistrationModule som er relevant her. 
Jeg tok uansett et søk på tilsvarende platformsjekker (søkte på 'cordova') i applikasjonen og erstattet alle disse med 'hybrid', da jeg regner med at det er tryggere.
https://ionicframework.com/docs/angular/platform
Denne feilen dukket opp da jeg flettet feature/add-common-project og develop siste gang, fordi develop dro med seg Capacitor, og Cordova-kjøremiljøet er ikke i bruk lengre.
> RO-1588: Byttet platform fra cordova til hybrid slik at riktig implementasjon av NewAttachmentService ble brukt

- src/app/modules/registration/pages/base.page.ts
- src/app/modules/registration/pages/snow/snow-profile/snow-profile.page.html
- src/app/modules/registration/pages/snow/snow-profile/snow-profile.page.ts
Fikser:
- Underskjema lagres
- Kan trigge snøprofil-preview når man har lagt til et lag
- Hindre at "undefined" legges til på registration request
Todo:
- Snøprofilplott preview feiler - sjekk hva plot server forventer
> RO-1593: Update base view registration after navigating from sub view ++

- src/app/modules/common-registration/services/add-new-attachment/file-attachment.service.ts
Dette er et problem både på Android 10 og iOS 15.
Det var to feil som begge har med at appen prøver å slette bildemappa til registreringa etter at den er sendt inn.
1. Hvis du ikke hadde bilder i registreringa, hadde du heller ingen bildemappe, så da feilet det når vi prøvde å slette en mappe som ikke eksisterte. Feilmelding fra OS'et var NOT_FOUND_ERR.
2. Hvis du hadde bilder i registreringa, feilet det fordi bildemappa inneholdt filer. Dette ga INVALID_MODIFICATION_ERR fra OS'et. Ble løst ved å kjøre et eget kall for rekursiv sletting
> RO-1615: Fikset feil ved sletting av lokale filer på tlf. etter innsending som gjorde at registrering hang igjen med feilmarkering

- package-lock.json
- package.json
- src/app/core/services/geo-position/geo-position.service.ts
- src/app/modules/gps-debug/components/gps-debug/gps-debug.component.html
- src/app/modules/gps-debug/components/gps-debug/gps-debug.component.ts
- src/app/modules/map/components/map/map.component.ts
- src/settings.model.ts
- src/settings.ts
Denne fiksen er forsøk på å få "fersk" GPS-posisjon så fort vi ber om det (når appen aktiveres f.eks.).
Har nå satt timeout til 1 sekund etter tips fra @jorgkv , og det så ut til å gjøre susen. Har også satt maximumAge til 0. Jeg skjønner ikke helt bakgrunnen for at maximumAge var satt til Infinity, men mulig at dette funket bra i tidligere versjoner av Android. Jeg synes ikke det er logisk at endring av timeout skulle ha noe å si for hvor raskt vi får posisjon første gang, men greit nok. Da blir funksjonaliteten mer lik den vi har på iPhone, som rapporterer posisjon ganske ofte (rundt 1 gang / sek?).
Her er dokumentasjon: https://capacitorjs.com/docs/apis/geolocation#positionoptions
NB! Siden de "gamle" innstillingene for posisjonering funka best på iOS, kjører vi kun de nye …
> RO 1623: Get position immediately on android
